version: '3.8'

services:
  open-logistics:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - MLX_ENABLED=false  # Disable MLX in container
    volumes:
      - ./data:/app/data
      - ./results:/app/results
    depends_on:
      - redis
      - postgres
    networks:
      - openlogistics-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - openlogistics-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=openlogistics
      - POSTGRES_USER=openlogistics
      - POSTGRES_PASSWORD=openlogistics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openlogistics-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - openlogistics-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - openlogistics-network

volumes:
  redis_data:
  postgres_data:
  grafana_data:

networks:
  openlogistics-network:
    driver: bridge
