site_name: Open Logistics Documentation
site_description: AI-Driven Air Defense Supply Chain Optimization Platform
site_author: Nik Jois
site_url: https://openlogistics.github.io/open-logistics/

repo_name: openlogistics/open-logistics
repo_url: https://github.com/openlogistics/open-logistics
edit_uri: edit/main/docs/

theme:
    name: material
    palette:
      - scheme: default
        primary: blue
        accent: blue
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: blue
        accent: blue
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    features:
      - navigation.tabs
      - navigation.sections
      - navigation.expand
      - navigation.top
      - search.highlight
      - search.share
      - content.code.annotate

plugins:
    - search
    - mermaid2

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdown_x.inlinehilite
    - pymdownx.snippets
    - pymdownx.tabbed:
        alternate_style: true
    - tables
    - toc:
        permalink: true

nav:
    - Home: index.md
    - User Guide:
      - Getting Started: user_guide/getting_started.md
      - Examples: user_guide/examples.md
      - Configuration: user_guide/configuration.md
    - API Reference:
      - Overview: api/index.md
      - MLX Optimizer: api/mlx_optimizer.md
      - Use Cases: api/use_cases.md
      - Configuration: api/configuration.md
    - Architecture:
      - Overview: architecture/overview.md
      - Clean Architecture: architecture/clean_architecture.md
      - MLX Integration: architecture/mlx_integration.md
      - SAP BTP Integration: architecture/sap_btp.md
    - Deployment:
      - Overview: deployment/index.md
      - Docker: deployment/docker.md
      - Kubernetes: deployment/kubernetes.md
      - Production: deployment/production.md

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/openlogistics/open-logistics
      - icon: fontawesome/brands/python
        link: https://pypi.org/project/open-logistics/ 