apiVersion: v1
kind: Secret
metadata:
  name: open-logistics-secrets
  namespace: openlogistics
type: Opaque
data:
  SECRET_KEY: $(echo -n "dev-secret-key-change-in-production" | base64)
  POSTGRES_PASSWORD: $(echo -n "openlogistics" | base64)
  REDIS_PASSWORD: $(echo -n "" | base64)
  SAP_BTP_CLIENT_SECRET: $(echo -n "sap-btp-client-secret" | base64)
